### ISSUE TITLE
FWIW: I Deleted Default Field Group, oh no!

### ISSUE THREAD

**Issue by Natetronn** [engram-design/FieldManager#3]
I just deleted the Default Field Group and all it's Fields so I could see how the import works. The import was successful but, no fields display because the Default Field Group doesn't exist any longer. I tried going to Settings > Fields to add in a group and receive an error at that point (probably because fields exist but, no groups exist.)

I was hoping when we export a whole group of fields that the group would go with it. That way it just creates it and adds the fields to the group on import. It would be nice if it asked us if we wanted to rename the group on import as well.

I noticed there was a dropdown for the group we want to add the fields to. In my case it was blank because no Group existed (I deleted it.) This seems like a good place to test for the existence of a Group/s and if one doesn't exist ask if we'd like to create it (or just create a Default one automagically maybe.)

OR and I'm just thinking out loud here, just don't allow us to delete the only field group that exists.

Now, I wouldn't actually have done this in production but, I did want to test things out and give you feedback on this just the same because I KNOW someone is actually going to go down this road because, well, they can. 

I'll manually add back in my group to the DB to get myself unstuck at this point but, I know others may not appreciate having to do that ;-)

**Comment by engram-design** [comment]
Well caught, I actually want to improve the import process into more of a mapping-style similar to [FeedMe](https://github.com/engram-design/FeedMe). This will allow you to define which groups you'd like fields to be allocated into, rather that putting all fields into a single group.

Short-term though, I'd like to be able to create a field group directly from the Import screen, which would be handy. Possibly even automagically as you suggest. Along with that, you should be able to specify a handle prefix for all the fields you import, just so there's no duplication (error) between other existing fields. This is only an issue when importing/exporting on the same site.

I've now added some error-handling so that you must specify a group.

I agree exporting groups would be beneficial - the problem being that what if you don't want to preserve the groups on the new site? In a boilerplate scenario, this would be fine, where you have a set group of default fields you want to use on every new site. But what if you want to pick a few, from different groups on one site, but have them all in one group on another? It's sort of an edge-case, but something that could be easily handled with the group-mapping above...

And thanks for the detailed description!

**Comment by Natetronn** [comment]
The addition of field mapping would be amazing! Have you thought about Combining FeedMe with FieldManager? Or would it be better to keep them separate for sanity sake? We were talking about this to a certain degree on Twitter in fact.

**Comment by engram-design** [comment]
I'd probably keep them separate, just because they have different goals mainly. As we were chatting, the thought did come to mind. It's possible!

**Comment by engram-design** [comment]
@Natetronn I've re-thought the importing process, and now includes mapping of fields. When importing, you can alter the field name, handle and set the group you want to import into.

As an added bonus, you can easily select all fields to go into one group, or go through and selectively set what goes where.

You can also add new field groups directly from the import screen :)

![screen shot 2015-05-02 at 11 02 33 pm](https://cloud.githubusercontent.com/assets/1221575/7441205/739f4d84-f120-11e4-8ee3-ace3084d59a8.png)

**Comment by engram-design** [comment]
Closing for now - hope you find the solution works for you @Natetronn :smiley:
