### ISSUE TITLE
Borked my entire install - Craft 3

### ISSUE THREAD

**Issue by CreateSean** [engram-design/FieldManager#48]
### Description
I just installed Craft 3 RC12 locally and then added in fieldmanager. All good. I then exported some fields from a C2 install and imported to the new C3 install. As soon as I did that my entire install is unusable. I can no longer access the control panel. The export file is in this dropbox link https://www.dropbox.com/s/wruzjfiraew5ub7/export.json?dl=0

Now any time I visit any page, front end or back end, I get the errors in this screenshot. https://www.dropbox.com/s/0hhkisjd3hgci3k/field-manager-errors.JPG?dl=0

### Steps to reproduce

1.
2.

### Additional info

- Plugin version: latest from the plugin store (I can't see version number because I no longer have access to my control panel)
- Craft version: 3 RC12

**Comment by engram-design** [comment]
I believe this is related to your asset fields containing a setting in Craft 2 that no longer exists in Craft 3. This causes this very nasty error (which is pretty overkill in my opinion) because it contains a database setting for something on the field, but no PHP property for that.

To get the control panel working again, just go to the `craft_fields` table and delete the "Contact Info" field. I'll push a change to address this issue shortly.

**Comment by engram-design** [comment]
This should be now fixed in [2.0.2](https://github.com/verbb/field-manager/releases/tag/2.0.2). Once you clear out those fields you've semi-imported, `composer update` before trying again.
