### ISSUE TITLE
Position Select in matrix not cloning or importing

### ISSUE THREAD

**Issue by marionnewlevant** [engram-design/FieldManager#9]
I have a matrix field with a block with a position select fieldtype. Three of the positions are turned on. When I clone the matrix, all positions are turned off in the clone. When I export the matrix, only the 'on' positions are in the json, but when I import that json, all of the positions are on.

**Comment by engram-design** [comment]
@marionnewlevant Its interesting in that the Position Select field seems to be a little special case. You'll find that even outside of Matrix, the settings aren't retained. I was actually aware of this oddity [#L44](https://github.com/engram-design/FieldManager/blob/master/fieldmanager/services/FieldManagerService.php#L44)

What's happening here is that the options aren't being imported properly, mainly due to the way the Position Select's `prepSettings()` field works.

While options are exported correctly as:

```
"options": [
    "left",
    "center",
    "right",
    "full"
]
```
When the get imported, they turn into:

```
"options": {
    0: "left",
    1: "center",
    2: "right",
    3: "full"
}
```

And because the Position Select only grabs the keys from this options array `array_keys(array_filter($settings['options']));`

You end up with:

```
"options": [
    0,
    1,
    2,
    3
]
```

In any case, this has been fixed in the [1.3.5](https://github.com/engram-design/FieldManager/releases/tag/1.3.5) release.
